### ISSUE TITLE
Quarter dates per company

### ISSUE THREAD

**Issue by markus080402** [alvarobartt/investpy#116] opened 2020-03-05 17:25 UTC
Would it be possible to get the quarter dates per company? 

60% of the companies follow the traditional calendar, i.e. Q1 is Jan-March, but about 40% of the companies, for example Apple end their Q4 on 28 of December, see below:

![ffff](https://user-images.githubusercontent.com/8713210/76006525-e554af00-5f0c-11ea-824e-73e327ee60d8.jpg)

![gggg](https://user-images.githubusercontent.com/8713210/76006660-1cc35b80-5f0d-11ea-9cce-faec7c75594d.jpg)

Since the information about when each company's financial year ends is available in investing.com , and also when each quarter ends, would it be possible for investpy to provide the quarterly periods (dates) per company?

For example, it could be added to the return paramameters of the function: 
investpy.stocks.get_stock_information(stock, country, as_json=False)

For example for AAPL:

stock_information = {
    "Stock Symbol": "AAPL",
    "Prev. Close": 267.25,
    "Todays Range": "263.45 - 268.25",
    "Revenue": 260170000000.00003,
    "Open": 267.27,
    "52 wk Range": "142 - 268.25",
    "EPS": 11.85,
    "Volume": 23693550.0,
    "Market Cap": 1173730000000.0,
    "Dividend (Yield)": "3.08 (1.15%)",
    "Average Vol. (3m)": 25609925.0,
    "P/E Ratio": 22.29,
    "Beta": 1.23,
    "1-Year Change": "47.92%",
    "Shares Outstanding": 4443236000.0,
    "Next Earnings Date": "04/02/2020"
    **"Financial Year Ends": "09/28/2019"
    "Q1 Ends": "12/28/2019"
    "Q2 Ends": "03/30/2019"
    "Q3 Ends": "06/29/2019"
    "Q4 Ends": "09/28/2019"**
}

**Comment by alvarob96** [comment] 2020-03-06 07:36
Hi @markus080402!

I did some research in Investing.com and decided to **include this feature soon since it provides a lot of useful information** as you already mentioned. Currently I am planning to include it once I finish solving current release issues, and develop it as a separate function maybe `investpy.financial_summary()` or something like that, I still need to figure it out.

Thank you for your issue! Stay tuned since I will be referencing this issue one I start its solving. :star: :octocat:

**Comment by markus080402** [comment] 2020-03-06 12:16
Hi @alvarob96 

Sounds awesome, thank you very much! 👍  💯 

With the new function would it be possible to also include the forecasted earnings and revenue, and also actual earnings and revenue from the same column? See below:

https://www.investing.com/equities/apple-computer-inc-earnings

![qwer](https://user-images.githubusercontent.com/8713210/76082753-5a2af600-5fac-11ea-8d75-ad5af2b8f2ae.jpg)

Regards,
Markus

**Comment by markus080402** [comment] 2020-03-23 08:21
Hi Alvaro!

It seems as quarterly financial data currently is not possible to fetch with investpy, for example quarterly revenue and earnings. Would be really useful to be able to fetch this data with investpy. :)

![image](https://user-images.githubusercontent.com/8713210/77296082-4f2fcf80-6ce7-11ea-9932-f3bf66c483b1.png)

![image](https://user-images.githubusercontent.com/8713210/77296176-83a38b80-6ce7-11ea-924d-2cc629761b70.png)

Regards,
Markus

**Comment by alvarobartt** [comment] 2020-04-06 09:39
Hi @markus080402, thank you for you patience, I have been really busy lately. Anyway, I just wanted to let you know that I have already developed the functions so as to retrieve all the data you are mentioning for stocks/equities, but I am still figuring out how to implement it and include it on **investpy**. So on, thjs feature will be included really soon so make sure to watch this issue since once closed you will be able to retrieve all this data using the investpy development version (which I will tell you later how to install it).

**Comment by markus080402** [comment] 2020-04-06 10:03
Hi Alvaro,

Sounds great, awesome job! :)

Looking forward to try out the new functionality!

Thanks
Markus

**Comment by alvarobartt** [comment] 2020-05-07 21:20
Hi @markus080402, as I already told you I am pretty busy, but since this is the very first unsolved investpy issue, I will try to close it tomorrow. So stay tuned, since you will be able to retrieve financial summary data really soon on the investpy development version. Thanks a lot for your patience!

**Comment by markus080402** [comment] 2020-05-08 10:42
Hi @alvarobartt , great, don't work too hard :)

Regarding all "get" functions, for example 

```
investpy.stocks.get_stock_information()
investpy.stocks.get_stock_company_profile()

```
etc

It would be convenient if they always returned the **isin**, since it is guaranteed to be unique globally.

Thanks and have a nice weekend,
Markus

**Comment by alvarobartt** [comment] 2020-05-08 11:09
Oh thanks a lot @markus080402! Could you please create this issue at #147, since I am planning to include a custom input type on all data retrieval functions so that users can specify the input field for those function such as the ISIN, the symbol or the name. Thank you again mate!

**Comment by alvarobartt** [comment] 2020-05-08 12:55
Hi again @markus080402, the feature is already available on the developer version but the docstrings and tests are still missing, so you can already use this function as it follows:

```python
import investpy

financial_summary = investpy.get_stock_financial_summary(stock='AAPL',
                                                         country='United States',
                                                         summary_type='income_statement',
                                                         period='annual')

print(financial_summary)
```
```{r, engine='python', count_lines}
            Total Revenue  Gross Profit  Operating Income  Net Income
Date                                                                 
2019-09-28         260174         98392             63930       55256
2018-09-29         265595        101839             70898       59531
2017-09-30         229234         88186             61344       48351
2016-09-24         215639         84263             60024       45687
```

And the available `summary_types` are: 'income_statement', 'balance_sheet' and 'cash_flow_statement'; and `period` values are: 'annual' or 'quarterly'.

Give me some feedback on its usage before I include it in the stable version! Regards!

**Comment by markus080402** [comment] 2020-05-08 15:44
Hi Alvaro,

Looks great!

Can you also include the following table? Report release dates, Period End,
EPS and EPS forecast, Revenue and Revenue forecast?

That would be very useful :)

[image: image.png]

Have a great weekend!

Regards,
Markus

Den fre 8 maj 2020 kl 14:55 skrev Álvaro Bartolomé <notifications@github.com

**Comment by alvarobartt** [comment] 2020-05-08 17:46
Hi @markus080402 I am unable to see the image, can you please post it again? Thanks!

**Comment by markus080402** [comment] 2020-05-08 18:58
Hi @alvarobartt 

Ah sorry, it is the same "earnings and eps"image snapshotted from investing.com that I added in an earlier messeage in this issue:

https://www.investing.com/equities/apple-computer-inc-earnings

![eps and forecasts](https://user-images.githubusercontent.com/8713210/81439297-772ba300-916e-11ea-9794-491be18b9be6.jpg)

Cheers!

**Comment by alvarobartt** [comment] 2020-05-09 11:38
Ok @markus080402, since including earnings data is a separate issue and, so on, a separate function, I suggest you to open another issue so as to include Stock Earnings data. Currently, I will be focused on solving the bugs or errors before including new features, but as soon as I solve all the current bugs I will develop that concrete functionality. Regards!

**Closed** 2020-05-09 12:13 UTC
Labels: enhancement, futurefix

**Comment by markus080402** [comment] 2020-05-09 14:59
Sounds good, created https://github.com/alvarobartt/investpy/issues/155

Cheers!

**Comment by markus080402** [comment] 2020-05-11 20:48
Hi @alvarobartt ,

Thanks for creating the investpy.get_stock_financial_summary() function!

Can we amend this function with two more arguments?

'isin' and 'exchange', or alternatively, include the isin and exchange in the return values, since now it is sometimes ambigious due to there can be the same symbol in the same country for multiple stocks.

The problem is similar to what is described in https://github.com/alvarobartt/investpy/issues/154

Thanks and regards,
Markus

**Comment by alvarobartt** [comment] 2020-05-11 20:56
Yes @markus080402 I already considered it. The stocks.csv updated static file will be available between tomorrow and the day after tomorrow. I will try to figure out how the input type decision will be.

Probably default values will be stock symbol, country and stock exchange, and one optional parameter to change the stock input type to either `name` or `isin`, I still need to study it anyway.

Thanks! From now on, all the additional input related issues will be described/reported in both #154 and #147.

**Comment by przemekr** [comment] 2020-07-24 18:37
Regarding the .get_stock_financial_summary():

stocks.py line 1431, I needed to change to:
            value = row.text_content().strip()
            data[curr_row].append(float(value) if value else 0)

as for some stocks the grossing information is missing, and you try to convert empty string to float.   Also  the function throws 'lxml.etree.ParserError' with message 'empty document' for some other stocks

**Comment by alvarobartt** [comment] 2020-11-05 08:48
Hi @przemekr!

First of all sorry for the delay, I'm checking the older investpy issues and I didn't get notified of that comment as I already closed the issue 😩 So sorry for that!

Could you please send me an example so as to reproduce that issue? If so you can either create a new one and let me know so as to include it on the v1.1 project board (as you have some sort of priority as this was one of the oldest unsolved issues) or you can just define it on here and I'll reopen this issue. Thanks a lot!
