### ISSUE TITLE
investpy.technical.moving_averages - 406 Not Acceptable

### ISSUE THREAD

**Issue by SladeSantos** [alvarobartt/investpy#275] opened 2021-01-25 15:08 UTC
Good afternoon,
Checks whether the function is closing after consultation.
#investpy.technical.moving_averages

Or if the problem is just the page outside the area:

https://www.investing.com/currencies/eur-usd

**Comment by alvarobartt** [comment] 2021-01-25 15:35
Hi @SladeSantos! Could you please provide more information? Like for example the sample Python call you are using to reproduce the error myself and try to solve it? Thanks! 👍🏻

**Comment by SladeSantos** [comment] 2021-01-25 15:42
In fact, the code was working normally. However, as soon as the page https://www.investing.com/currencies/eur-usd went down, the API was no longer able to fetch the data.

At https://www.investing.com/currencies/eur-usd, when trying to access the error is displayed: 406 Not Acceptable

Anyway, follow the code:

mav1hr = investpy.technical.moving_averages (name = 'EUR / USD', country = None, product_type = 'currency_cross', interval = '5mins')
print (mav1hr.head ())

**Comment by alvarobartt** [comment] 2021-01-25 15:47
Ok, cool @SladeSantos! Will try to reproduce the error and let you know if there's any fix for this, as the HTTP 406 code is always related to an Investing.com limitation whenever you send too many requests. But let me check it! 👍🏻 

BTW is the error still happening?

**Comment by SladeSantos** [comment] 2021-01-25 16:30
The error persists!
But, I believe this is it. I was testing the code and made several requests in a row.

Therefore, I questioned whether at each request he completed the process.

I am currently making an appointment every minute.

**Comment by alvarobartt** [comment] 2021-01-25 16:39
I think you need to wait before sending more requests as Investing.com limits you for some hours, so before sending those requests make sure that you can access https://www.investing.com/equities/ without any problem. Otherwise the only solution is to wait 😩 and next time try to wait more time between each request as Investing.com has some sever limitations regarding the requests to their stocks/equities functionality...

**Comment by alvarobartt** [comment] 2021-01-25 16:40
BTW let me know if you need anything else or if the error persists even though you can access the URL without any issues, and if you don't need anything else, please close this issue! 🤗

**Comment by SladeSantos** [comment] 2021-01-25 16:42
Thank you for your attention and clarification!

This was basically the problem! I will follow the suggested recommendations;)

**Closed** 2021-01-25 16:42 UTC
Labels: bug

**Comment by Hcevahir34** [comment] 2022-05-30 17:33
Hi! 
Could you solve this problem? Because I'm a new investpy user and though I've installed this library, I couldn't run the below code. I got this error:

"import investpy
df = investpy.get_stock_historical_data(stock='AAPL',
country='United States',
from_date='01/01/2010',
to_date='01/01/2020')
print(df.head())"

".........in get_stock_historical_data
    raise ConnectionError(
ConnectionError: ERR#0015: error 503, try again later."
  
![image](https://user-images.githubusercontent.com/105820939/171038847-9010b213-a222-431b-a9ab-78b5cf510915.png)
