### ISSUE TITLE
Error Fund not found

### ISSUE THREAD

**Issue by neodani** [alvarobartt/investpy#148] opened 2020-04-24 09:56 UTC
Hi,

I am using the library without problems, but when I want to list this fund and get its quotes I can't.

This works
search_results = investpy.search_funds('isin','ES0110407097')
print(search_results.head())

But this not
search_results = investpy.search_funds('isin','ES0173985005')
print(search_results.head())
RuntimeError: ERR#0043: no results were found for the introduced isin.

The fund exists
https://www.investing.com/funds/es0173985005

I've tried other ways to list it as the symbol but it didn't work either
search_results = investpy.search_funds('symbol','0P0001F2GI')
print(search_results.head())

Do you know where the problem is?

Thank you

**Comment by alvarobartt** [comment] 2020-04-24 10:15
Hi @neodani, thanks for the feedback!

This is a common "problem" while using investpy, since as I already mentioned in the FAQs section (which can be found at: https://investpy.readthedocs.io/faq.html#what-do-i-do-if-the-financial-product-i-am-looking-for-is-not-indexed-in-investpy) some data indexed at Investing.com is not available on investpy, since it is not properly indexed and scrapers are not able to store it. But since it is an Investing.com problem, it has "no solution" on investpy.

Anyway, since this feature is not already merged into the master branch, I suggest you to install the development version using the command:

``pip install git+https://github.com/alvarobartt/investpy.git@developer``

Once you install it, you can use the following piece of code:

![image](https://user-images.githubusercontent.com/36760800/80201905-27ed5a80-8625-11ea-990c-d0efb0b55813.png)

Hope this helped you! Make sure to follow me and star the repo if you found it useful so as to get notified of all conversations and investpy releases! :star: :octocat:

**Closed by alvarobartt** 2020-04-24 10:15 UTC
Labels: question

**Comment by neodani** [comment] 2020-04-26 14:36
Something wrong...

C:\WINDOWS\system32>pip install git+
https://github.com/alvarobartt/investpy.git@developer
Collecting git+https://github.com/alvarobartt/investpy.git@developer
  Cloning https://github.com/alvarobartt/investpy.git (to revision
developer) to
 c:\users\dani\appdata\local\temp\pip-req-build-55chko4j
  Running command git clone -q https://github.com/alvarobartt/investpy.git
'C:\U
sers\Dani\AppData\Local\Temp\pip-req-build-55chko4j'
  Running command git checkout -b developer --track origin/developer
  D     investpy/utils/aux.py
  Branch 'developer' set up to track remote branch 'developer' from
'origin'.
  error: unable to stat just-written file investpy/utils/aux.py: No such
file or
 directory
  Switched to a new branch 'developer'
Requirement already satisfied: Unidecode>=1.1.1 in c:\program
files\python36\lib
\site-packages (from investpy==1.0) (1.1.1)
Requirement already satisfied: setuptools>=41.2.0 in c:\program
files\python36\l
ib\site-packages (from investpy==1.0) (46.0.0)
Requirement already satisfied: numpy>=1.17.2 in c:\program
files\python36\lib\si
te-packages (from investpy==1.0) (1.18.1)
Requirement already satisfied: pandas>=0.25.1 in c:\program
files\python36\lib\s
ite-packages (from investpy==1.0) (1.0.1)
Requirement already satisfied: lxml>=4.4.1 in c:\program
files\python36\lib\site
-packages (from investpy==1.0) (4.5.0)
Requirement already satisfied: requests>=2.22.0 in c:\program
files\python36\lib
\site-packages (from investpy==1.0) (2.23.0)
Requirement already satisfied: pytz>=2017.2 in c:\program
files\python36\lib\sit
e-packages (from pandas>=0.25.1->investpy==1.0) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\program
files\python
36\lib\site-packages (from pandas>=0.25.1->investpy==1.0) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\program
files\python36\l
ib\site-packages (from requests>=2.22.0->investpy==1.0) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in c:\program
files\python36\lib\sit
e-packages (from requests>=2.22.0->investpy==1.0) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program
files\python36\li
b\site-packages (from requests>=2.22.0->investpy==1.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in
c:\pro
gram files\python36\lib\site-packages (from
requests>=2.22.0->investpy==1.0) (1.
25.8)
Requirement already satisfied: six>=1.5 in c:\program
files\python36\lib\site-pa
ckages (from python-dateutil>=2.6.1->pandas>=0.25.1->investpy==1.0) (1.11.0)
Installing collected packages: investpy
  Attempting uninstall: investpy
    Found existing installation: investpy 0.9.14
    Uninstalling investpy-0.9.14:
      Successfully uninstalled investpy-0.9.14
    Running setup.py install for investpy ... done
Successfully installed investpy-1.0

C:\WINDOWS\system32>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit
(AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import investpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\investpy\__init__.py",
line
7, in <module>
    from .stocks import get_stocks, get_stocks_list, get_stocks_dict,
get_stock_
countries, get_stock_recent_data, \
  File "C:\Program Files\Python36\lib\site-packages\investpy\stocks.py",
line 14
, in <module>
    from .utils.aux import random_user_agent
ModuleNotFoundError: No module named 'investpy.utils.aux'

Any idea?

Regards

**Comment by alvarobartt** [comment] 2020-04-26 14:57
Hi, as you can see in the error trace, the system says that the clone process could not be properly done while retrieving Python files stored under `utils/`. I tested it on Windows, Mac and Linux and it works perfectly for me, maybe it was just a random error. So I suggest you to try it again, after uninstalling the previous investpy version:

```
pip uninstall investpy
pip install git+https://github.com/alvarobartt/investpy.git@developer --upgrade
```

If the error persists, let me know.

**Comment by neodani** [comment] 2020-04-29 15:12
Weird... still not working...

C:\WINDOWS\system32>pip uninstall investpy
Found existing installation: investpy 0.9.14
Uninstalling investpy-0.9.14:
  Would remove:

c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages\investpy-0.9.14-py3.6.egg-info

c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages\investpy\*

c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages\tests\*
Proceed (y/n)? y
  Successfully uninstalled investpy-0.9.14

C:\WINDOWS\system32>pip install git+
https://github.com/alvarobartt/investpy.git@developer --upgrade
Collecting git+https://github.com/alvarobartt/investpy.git@developer
  Cloning https://github.com/alvarobartt/investpy.git (to revision
developer) to c:\users\neodani\appdata\local\temp\pip-req-build-mcvc6pwo
  Running command git clone -q https://github.com/alvarobartt/investpy.git
'C:\Users\neodani\AppData\Local\Temp\pip-req-build-mcvc6pwo'
  Running command git checkout -b developer --track origin/developer
  D     investpy/utils/aux.py
  Branch 'developer' set up to track remote branch 'developer' from
'origin'.
  error: unable to create file investpy/utils/aux.py: No such file or
directory
  Switched to a new branch 'developer'
Requirement already satisfied, skipping upgrade: Unidecode>=1.1.1 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (1.1.1)
Requirement already satisfied, skipping upgrade: setuptools>=41.2.0 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (46.1.3)
Requirement already satisfied, skipping upgrade: numpy>=1.17.2 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (1.18.2)
Requirement already satisfied, skipping upgrade: pandas>=0.25.1 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (0.25.3)
Requirement already satisfied, skipping upgrade: lxml>=4.4.1 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (4.5.0)
Requirement already satisfied, skipping upgrade: requests>=2.22.0 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from investpy==1.0) (2.23.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from pandas>=0.25.1->investpy==1.0) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from pandas>=0.25.1->investpy==1.0) (2.7.4)
Requirement already satisfied, skipping upgrade:
urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from requests>=2.22.0->investpy==1.0) (1.22)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from requests>=2.22.0->investpy==1.0) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from requests>=2.22.0->investpy==1.0) (2.6)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from requests>=2.22.0->investpy==1.0) (2017.11.5)
Requirement already satisfied, skipping upgrade: six>=1.5 in
c:\users\neodani\appdata\local\programs\python\python36\lib\site-packages
(from python-dateutil>=2.6.1->pandas>=0.25.1->investpy==1.0) (1.14.0)
Building wheels for collected packages: investpy
  Building wheel for investpy (setup.py) ... done
  Created wheel for investpy: filename=investpy-1.0-py3-none-any.whl
size=4481698
sha256=4ef868dc20b00092b5381baca0ee0fba324b8371fe73d3e45b8a64e287cc1c69
  Stored in directory:
C:\Users\neodani\AppData\Local\Temp\pip-ephem-wheel-cache-ehhvsznc\wheels\51\a8\a9\dbe3f86e5199a630a636a4ee6fc655e3f438baa3c85d409a1a
Successfully built investpy
Installing collected packages: investpy
Successfully installed investpy-1.0

C:\WINDOWS\system32>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import investpy
C:\Users\neodani\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\_distributor_init.py:32:
UserWarning: loaded more than 1 DLL from .libs:
C:\Users\neodani\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
C:\Users\neodani\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"C:\Users\neodani\AppData\Local\Programs\Python\Python36\lib\site-packages\investpy\__init__.py",
line 7, in <module>
    from .stocks import get_stocks, get_stocks_list, get_stocks_dict,
get_stock_countries, get_stock_recent_data, \
  File
"C:\Users\neodani\AppData\Local\Programs\Python\Python36\lib\site-packages\investpy\stocks.py",
line 14, in <module>
    from .utils.aux import random_user_agent
ModuleNotFoundError: No module named 'investpy.utils.aux'
>>>

Any sugestion?

Regards

**Comment by Fetix** [comment] 2020-06-20 12:14
Hi guys,
ran into the same error when I couldn't poll stock data from investing.
Tried to run the developer version of investpy and follow the above instructions.

The error seems to be caused by aux.py. Windows doesn't allow for a file to have the name "aux". The issue does not show up in the current master branch, there the file is called "auxiliary.py".

Cheers
Felix
